import type { Config } from "tailwindcss";

const config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    colors: {
      background: "var(--color-background)",
      foreground: "var(--color-foreground)",
      cyan: {
        "50": "var(--color-cyan-50)",
        "100": "var(--color-cyan-100)",
        "200": "var(--color-cyan-200)",
        "300": "var(--color-cyan-300)",
        "400": "var(--color-cyan-400)",
        "500": "var(--color-cyan-500)",
        "600": "var(--color-cyan-600)",
        "700": "var(--color-cyan-700)",
        "800": "var(--color-cyan-800)",
        "900": "var(--color-cyan-900)",
        "950": "var(--color-cyan-950)",
      },
      pink: {
        "50": "var(--color-pink-50)",
        "100": "var(--color-pink-100)",
        "200": "var(--color-pink-200)",
        "300": "var(--color-pink-300)",
        "400": "var(--color-pink-400)",
        "500": "var(--color-pink-500)",
        "600": "var(--color-pink-600)",
        "700": "var(--color-pink-700)",
        "800": "var(--color-pink-800)",
        "900": "var(--color-pink-900)",
        "950": "var(--color-pink-950)",
      },
      primary: {
        "50": "var(--color-primary-50)",
        "100": "var(--color-primary-100)",
        "200": "var(--color-primary-200)",
        "300": "var(--color-primary-300)",
        "400": "var(--color-primary-400)",
        "500": "var(--color-primary-500)",
        "600": "var(--color-primary-600)",
        "700": "var(--color-primary-700)",
        "800": "var(--color-primary-800)",
        "900": "var(--color-primary-900)",
        "950": "var(--color-primary-950)",
      },
      purple: {
        "50": "var(--color-purple-50)",
        "100": "var(--color-purple-100)",
        "200": "var(--color-purple-200)",
        "300": "var(--color-purple-300)",
        "400": "var(--color-purple-400)",
        "500": "var(--color-purple-500)",
        "600": "var(--color-purple-600)",
        "700": "var(--color-purple-700)",
        "800": "var(--color-purple-800)",
        "900": "var(--color-purple-900)",
        "950": "var(--color-purple-950)",
      },
      black: "var(--color-black)",
      white: "var(--color-white)",
      line: "var(--color-line-color)",
      lineDark: "var(--color-line-color-dark)",
    },
    fontFamily: {
      sans: ["var(--font-inter)", "Arial", "Helvetica", "sans-serif"],
      heading: ["var(--font-urbanist)", "var(--font-inter)", "Arial", "Helvetica", "sans-serif"],
      mono: ["var(--font-geist-mono)", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
    },
  },
  plugins: []
} satisfies Config;

export default config;